export const environment = {
  production: true,
  listbankurl:'http://localhost:8585/banks/',
  updatebankurl:'http://localhost:8585/banks/UpdateBank',
  addbankurl:'http://localhost:8585/banks/AddBank',
  searchbankurl:'http://localhost:8585/banks/search',
  listerrorurl:'http://localhost:8585/error/',
  updateerrorurl:'http://localhost:8585/error/UpdateErrorCode',
  adderrorcodeurl:'http://localhost:8585/error/AddErrorCode',
  searcherrorcodeurl:'http://localhost:8585/error/search',
  checkcodeurl:'http://localhost:8585/banks/CheckCode',
  dashboardurl:'http://localhost:8585/dashboard',
  searchdashboardurl:'http://localhost:8585/dashboard/search',
  usersurl:'http://localhost:8585/users',
  rolesurl:'http://localhost:8585/users/roles',
  updateuserprofileurl:'http://localhost:8585/users/UpdateUser',
  addnewuserurl:'http://localhost:8585/users/AddUser',
  searchuserurl:'http://localhost:8585/users/search',
  resetuserurl:'http://localhost:8585/users/ResetPassword',
  colorcodeurl:'http://localhost:8585/display/',
  updatecoloururl:'http://localhost:8585/display/UpdateDisplaySettings',
  addcoloururl:'http://localhost:8585/display/addNewDisplaySettings',
  dashboardanalytics:'http://localhost:8585/dashboard/analytics',
  authurl:'http://localhost:8585/auth/login'
};
